services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./tuftecms:/app/tuftecms
      - ./engine.py:/app/engine.py
    restart: unless-stopped
    command: ["uvicorn", "engine:api", "--host", "0.0.0.0", "--port", "8000", "--reload", "--reload-dir", "/app/tuftecms", "--reload-dir", "/app/data"]
