# fly.toml app configuration file generated for kr-website-icy-sea-7069 on 2024-08-12T16:11:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kr-website-icy-sea-7069'
primary_region = 'iad'

[build]

[deploy]
strategy = "bluegreen"

[http_service]
internal_port = 8000
force_https = true
auto_stop_machines = 'off'
auto_start_machines = true
min_machines_running = 1
processes = ['app']

[checks]
  [checks.web]
    type = "http"
    grace_period = "5s"
    interval = "10s"
    method = "get"
    path = "/"
    timeout = "2s"

[[vm]]
memory = '2gb'
cpu_kind = 'shared'
cpus = 2
